// 스카이젠 - 하늘섬 군도 : behaviour pack script (@minecraft/server 2.0, @minecraft/server-ui 2.0)
// Generated by sky_pack.py: DATA below holds every coordinate of the world (generators, plots, zones...).
import { world, system, ItemStack, ItemLockMode, GameMode, DisplaySlotId, ObjectiveSortOrder, BlockPermutation } from "@minecraft/server";
import { ActionFormData, MessageFormData } from "@minecraft/server-ui";

const DATA = __DATA__;
const SHOPS = __SHOPS__;
const SELL = __SELL__;

const OW = () => world.getDimension("overworld");
const ADMIN_TAG = "sky_admin";
const NIGHT_START = 13000, NIGHT_END = 23000;
const BAN_MSG = (n) => "§c[보안] §f" + n + " 플레이어가 핵을 사용하여 영구밴 됬습니다";
const MENU_ITEM = "minecraft:compass";
const MENU_NAME = "§r§l§b스카이젠 메뉴";
const START_MONEY = 100;

// ------------------------------------------------------------------ small helpers
const key3 = (x, y, z) => x + "," + y + "," + z;
const lower = (v) => String(v).toLowerCase();
function inBox(l, b, m = 0) {
  return l.x >= b[0] + m && l.x < b[3] + 1 - m && l.y >= b[1] && l.y < b[4] + 1 && l.z >= b[2] + m && l.z < b[5] + 1 - m;
}
function blockIn(bx, by, bz, b) {
  return bx >= b[0] && bx <= b[3] && by >= b[1] && by <= b[4] && bz >= b[2] && bz <= b[5];
}
function isAdmin(p) {
  try {
    if (p.hasTag(ADMIN_TAG)) return true;
    const m = lower(p.getGameMode());
    return m === "creative" || m === "spectator";
  } catch (e) { return false; }
}
function getBlock(x, y, z) {
  try { return OW().getBlock({ x, y, z }); } catch (e) { return undefined; }
}
function setBlock(x, y, z, type) {
  const b = getBlock(x, y, z);
  if (!b) return false;
  try { b.setType(type); return true; } catch (e) { return false; }
}
function cmd(c) {
  try { return OW().runCommand(c); } catch (e) { return undefined; }
}
function fmt(n) { return String(Math.floor(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ","); }
function tp(p, d, yaw) {
  try {
    p.teleport({ x: d[0] + (Number.isInteger(d[0]) ? 0.5 : 0), y: d[1], z: d[2] + (Number.isInteger(d[2]) ? 0.5 : 0) },
      { dimension: OW(), rotation: { x: 0, y: yaw ?? d[3] ?? 0 } });
  } catch (e) { }
}
function isNight() {
  const t = world.getTimeOfDay();
  return t >= NIGHT_START && t < NIGHT_END;
}
function store(key, def) {
  try {
    const v = world.getDynamicProperty(key);
    return v === undefined ? def : JSON.parse(v);
  } catch (e) { return def; }
}
function save(key, v) {
  try { world.setDynamicProperty(key, JSON.stringify(v)); } catch (e) { }
}
async function showForm(p, form) {
  for (let i = 0; i < 20; i++) {
    const r = await form.show(p);
    if (r.canceled && lower(r.cancelationReason) === "userbusy") {
      await new Promise((res) => system.runTimeout(res, 10));
      continue;
    }
    return r;
  }
  return { canceled: true };
}

// ------------------------------------------------------------------ money
function moneyObj() {
  let o = world.scoreboard.getObjective("money");
  if (!o) o = world.scoreboard.addObjective("money", "§6§l돈 (원)");
  return o;
}
function money(p) {
  try { return moneyObj().getScore(p) ?? 0; } catch (e) { return 0; }
}
function addMoney(p, n) {
  try { moneyObj().setScore(p, Math.max(0, money(p) + n)); } catch (e) { }
}

// ------------------------------------------------------------------ zones
const SAFE = DATA.safe;           // [x1,y1,z1,x2,y2,z2,island]
function safeZoneOf(l) {
  for (const b of SAFE) if (inBox(l, b)) return b[6];
  return undefined;
}
function furnaceRoomOf(l) {
  for (const r of DATA.furnace) if (inBox(l, r.box, 0.0)) return r;
  return undefined;
}

// ------------------------------------------------------------------ plots
let PLOTS = {};            // id -> {owner, ownerId, since}      (loaded in init: no world access at load time)
let BANS = [];             // [{name, id, at, reason}]
let PENDING_RESET = [];    // plot ids waiting for their blocks to be cleared
const PLOT_BY_ID = {};
for (const p of DATA.plots) PLOT_BY_ID[p.id] = p;
function plotAt(bx, by, bz) {
  for (const p of DATA.plots) if (blockIn(bx, by, bz, p.interior)) return p;
  return undefined;
}
function plotOfPlayerPos(l) {
  for (const p of DATA.plots) if (inBox(l, p.zone, 0.3)) return p;
  return undefined;
}
function owns(pl, plot) {
  const o = PLOTS[plot.id];
  return !!o && (o.ownerId === pl.id || o.owner === pl.name);
}
function plotOf(pl) {
  for (const id in PLOTS) {
    const o = PLOTS[id];
    if (o.ownerId === pl.id || o.owner === pl.name) return PLOT_BY_ID[id];
  }
  return undefined;
}

function isPlotButton(bx, by, bz) {
  for (const p of DATA.plots) {
    if ((bx === p.btnOut[0] && by === p.btnOut[1] && bz === p.btnOut[2]) ||
      (bx === p.btnIn[0] && by === p.btnIn[1] && bz === p.btnIn[2])) return true;
  }
  return false;
}
function placeButtons(pl) {
  // the inside button stands in the plot interior: a reset clears it, so it is put back here
  [[pl.btnOut, pl.btnFace[0]], [pl.btnIn, pl.btnFace[1]]].forEach(([q, face]) => {
    const b = getBlock(q[0], q[1], q[2]);
    if (!b || b.typeId === "minecraft:stone_button") return;
    try { b.setPermutation(BlockPermutation.resolve("minecraft:stone_button", { facing_direction: face })); } catch (e) { }
  });
}
function plotEntry(pl) {
  // the owner may have built over the landing spot: climb to the first 2-high gap
  const [x, y, z, yaw] = pl.inside;
  for (let yy = y; yy < pl.interior[4]; yy++) {
    const f = getBlock(x, yy, z), h = getBlock(x, yy + 1, z);
    if (!f || !h) break;
    if (f.isAir && h.isAir) return [x, yy, z, yaw];
  }
  return pl.inside;
}

// ------------------------------------------------------------------ generators
const GENS = {};
for (const g of DATA.gens) GENS[key3(g[0], g[1], g[2])] = g;   // [x,y,z,type,kind,regen]
const pendingGen = new Map();       // key -> tick when it may grow back
function restoreGen(k) {
  const g = GENS[k];
  if (!g) return true;
  const b = getBlock(g[0], g[1], g[2]);
  if (!b) return false;
  try {
    if (b.typeId !== g[3]) b.setType(g[3]);
    return true;
  } catch (e) { return false; }
}
function sweepGens() {
  const now = system.currentTick;
  for (const k in GENS) {
    const due = pendingGen.get(k);
    if (due !== undefined && due > now) continue;
    const g = GENS[k];
    const b = getBlock(g[0], g[1], g[2]);
    if (!b) continue;
    if (b.typeId !== g[3] && (b.typeId === "minecraft:bedrock" || b.typeId === "minecraft:air")) {
      try { b.setType(g[3]); pendingGen.delete(k); } catch (e) { }
    } else if (due !== undefined) pendingGen.delete(k);
  }
}

// ------------------------------------------------------------------ protection
const CONTAINERS = ["chest", "trapped_chest", "barrel", "shulker_box", "hopper", "dropper", "dispenser", "chiseled_bookshelf",
  "flower_pot", "lectern", "decorated_pot", "brewing_stand", "cauldron", "composter", "jukebox", "campfire", "soul_campfire",
  "_bed", "cake", "frame", "noteblock", "beacon", "respawn_anchor", "crafter", "lever", "daylight_detector", "repeater",
  "comparator", "bell", "vault", "trial_spawner", "furnace", "blast_furnace", "smoker", "sign", "end_portal_frame"];
const UTILITY = ["crafting_table", "enchanting_table", "anvil", "grindstone", "smithing_table", "stonecutter_block",
  "loom", "cartography_table", "ender_chest", "_door", "_trapdoor", "fence_gate", "_button"];
const MODIFY_ITEMS = ["bucket", "flint_and_steel", "fire_charge", "bone_meal", "shears", "_hoe", "_shovel", "_axe", "brush",
  "honeycomb", "spawn_egg", "ender_eye", "glass_bottle", "potion", "dye", "ink_sac"];
const BANNED_USE = ["minecraft:ender_pearl", "minecraft:chorus_fruit", "minecraft:wind_charge"];
const lastWarn = new Map();
function warn(p, text) {
  const t = system.currentTick;
  if ((lastWarn.get(p.id) ?? -100) + 30 > t) return;
  lastWarn.set(p.id, t);
  system.run(() => { try { p.onScreenDisplay.setActionBar(text); } catch (e) { } });
}
function inFurnaceUse(bx, by, bz) {
  for (const r of DATA.furnace) for (const f of r.furnaces) if (f[0] === bx && f[1] === by && f[2] === bz) return true;
  return false;
}
function buildAllowed(p, bx, by, bz) {
  const plot = plotAt(bx, by, bz);
  return plot && owns(p, plot);
}

world.beforeEvents.playerBreakBlock.subscribe((ev) => {
  const p = ev.player, b = ev.block;
  if (isAdmin(p)) return;
  const k = key3(b.x, b.y, b.z);
  if (GENS[k]) {
    if (b.typeId === "minecraft:bedrock") ev.cancel = true;
    return;
  }
  if (isPlotButton(b.x, b.y, b.z)) { ev.cancel = true; warn(p, "§c집터 출입 버튼은 부술 수 없어요"); return; }
  if (buildAllowed(p, b.x, b.y, b.z)) return;
  ev.cancel = true;
  const plot = plotAt(b.x, b.y, b.z);
  warn(p, plot ? "§c다른 사람의 집터입니다" : "§c여기서는 블록을 부술 수 없어요 (생성기 · 내 집터만 가능)");
});

world.afterEvents.playerBreakBlock.subscribe((ev) => {
  const b = ev.block;
  const k = key3(b.x, b.y, b.z);
  const g = GENS[k];
  if (!g) return;
  try { b.setType("minecraft:bedrock"); } catch (e) { }
  pendingGen.set(k, system.currentTick + g[5] * 20);
  system.runTimeout(() => { if (restoreGen(k)) pendingGen.delete(k); }, g[5] * 20);
});

world.afterEvents.playerPlaceBlock.subscribe((ev) => {
  const p = ev.player, b = ev.block;
  if (isAdmin(p)) return;
  if (buildAllowed(p, b.x, b.y, b.z)) return;
  let item;
  try { item = b.getItemStack(1); } catch (e) { item = undefined; }
  try { b.setType("minecraft:air"); } catch (e) { }
  if (item) {
    try { p.getComponent("minecraft:inventory").container.addItem(item); } catch (e) { }
  }
  warn(p, "§c블록은 내 집터 안에만 놓을 수 있어요");
});

world.beforeEvents.playerInteractWithBlock.subscribe((ev) => {
  const p = ev.player, b = ev.block;
  const held = ev.itemStack;
  if (held && held.typeId === MENU_ITEM && held.nameTag === MENU_NAME) {
    // menu item used while looking at a block (2.x has no itemUseOn event)
    ev.cancel = true;
    if (ev.isFirstEvent !== false) system.run(() => menuForm(p));
    return;
  }
  if (isAdmin(p)) return;
  const plot = plotAt(b.x, b.y, b.z);
  if (plot) {
    if (!owns(p, plot)) { ev.cancel = true; warn(p, "§c다른 사람의 집터입니다"); }
    return;
  }
  const id = b.typeId.replace("minecraft:", "");
  const item = ev.itemStack ? ev.itemStack.typeId.replace("minecraft:", "") : "";
  if (item && MODIFY_ITEMS.some((s) => item.includes(s))) {
    ev.cancel = true;
    return;
  }
  if (UTILITY.some((s) => id.includes(s))) return;
  if (id.includes("furnace") || id === "smoker") {
    if (inFurnaceUse(b.x, b.y, b.z)) return;
  }
  if (CONTAINERS.some((s) => id.includes(s))) ev.cancel = true;
});

world.beforeEvents.itemUse.subscribe((ev) => {
  const p = ev.source;
  if (!p || isAdmin(p)) return;
  if (BANNED_USE.includes(ev.itemStack.typeId)) {
    ev.cancel = true;
    warn(p, "§c이 서버에서는 사용할 수 없는 아이템입니다");
  }
});

world.beforeEvents.explosion.subscribe((ev) => { ev.cancel = true; });

// ------------------------------------------------------------------ PvP: day / night + safe zones
const lastPvpHit = new Map();
world.beforeEvents.entityHurt.subscribe((ev) => {
  const v = ev.hurtEntity;
  if (!v || v.typeId !== "minecraft:player") return;
  const src = ev.damageSource;
  let att = src && src.damagingEntity;
  if (!att || att.typeId !== "minecraft:player") return;
  if (att.id === v.id) return;
  if (!isNight() || safeZoneOf(v.location) || safeZoneOf(att.location)) {
    ev.cancel = true;
    return;
  }
  lastPvpHit.set(v.id, system.currentTick);
  lastPvpHit.set(att.id, system.currentTick);
});
function inCombat(p) {
  return isNight() && (lastPvpHit.get(p.id) ?? -1000) + 200 > system.currentTick;
}

let nightState = undefined;
function applyTime(announce) {
  const night = isNight();
  if (night === nightState) return;
  nightState = night;
  try {
    world.gameRules.pvp = night;
    world.gameRules.keepInventory = !night;
  } catch (e) {
    cmd("gamerule pvp " + night);
    cmd("gamerule keepinventory " + !night);
  }
  if (!announce) return;
  for (const p of world.getPlayers()) {
    try {
      if (night) {
        p.onScreenDisplay.setTitle("§c§l밤이 되었습니다", { subtitle: "§fPvP 가능 · 죽으면 아이템을 떨어뜨려요", fadeInDuration: 10, stayDuration: 60, fadeOutDuration: 20 });
        p.playSound("mob.wither.spawn", { volume: 0.4 });
      } else {
        p.onScreenDisplay.setTitle("§e§l아침이 밝았습니다", { subtitle: "§fPvP 불가 · 인벤토리 보호", fadeInDuration: 10, stayDuration: 60, fadeOutDuration: 20 });
        p.playSound("random.levelup", { volume: 0.6 });
      }
    } catch (e) { }
  }
  world.sendMessage(night ? "§c[스카이젠] 밤이 되었습니다. 안전구역 밖에서는 PvP가 가능하고, 죽으면 아이템을 잃습니다."
    : "§e[스카이젠] 아침입니다. PvP가 꺼지고 인벤토리가 보호됩니다.");
}

// ------------------------------------------------------------------ bans
function isBanned(p) {
  return BANS.some((b) => b.id === p.id || b.name === p.name);
}
function ban(p, reason) {
  if (isBanned(p)) return;
  BANS.push({ name: p.name, id: p.id, at: Date.now(), reason });
  save("sky:bans", BANS);
  world.sendMessage(BAN_MSG(p.name));
  const r = cmd('kick "' + p.name.replace(/"/g, "") + '" §c핵 사용으로 영구밴 되었습니다');
  if (!r || !r.successCount) {
    // single-player host cannot be kicked: at least throw them out of the plot
    tp(p, DATA.arrivals.hub);
  }
}
const strikes = new Map();
const spawnTick = new Map();
function banCheck() {
  const now = system.currentTick;
  for (const p of world.getPlayers()) {
    if (isAdmin(p)) { strikes.delete(p.id); continue; }
    if ((spawnTick.get(p.id) ?? -1000) + 100 > now) continue;      // grace right after (re)spawning
    const plot = plotOfPlayerPos(p.location);
    if (plot && !owns(p, plot)) {
      const n = (strikes.get(p.id) ?? 0) + 1;
      strikes.set(p.id, n);
      if (n >= 2) ban(p, "plot " + plot.id);
    } else strikes.delete(p.id);
  }
}

// ------------------------------------------------------------------ furnace rooms
const roomOcc = {};       // id -> Set of player ids
function furnaceTick() {
  const players = world.getPlayers();
  for (const r of DATA.furnace) {
    const prev = roomOcc[r.id] ?? new Set();
    const inside = players.filter((p) => inBox(p.location, r.box, 0.0));
    const next = new Set();
    for (const p of inside) {
      if (prev.size > 0 && !prev.has(p.id) && !isAdmin(p)) {
        tp(p, r.out);
        try { p.onScreenDisplay.setActionBar("§c다른 사람이 사용 중인 화로방입니다"); } catch (e) { }
        continue;
      }
      next.add(p.id);
    }
    if ((prev.size > 0) !== (next.size > 0)) {
      setBlock(r.lamp[0], r.lamp[1], r.lamp[2], next.size > 0 ? "minecraft:red_concrete" : "minecraft:lime_concrete");
      if (next.size === 1 && prev.size === 0) {
        for (const p of inside) try { p.onScreenDisplay.setActionBar("§a개인 화로방 " + r.id + " - 혼자 쓰는 중"); } catch (e) { }
      }
    }
    roomOcc[r.id] = next;
  }
}

// ------------------------------------------------------------------ portals
const portalTime = new Map();
const tpCooldown = new Map();
function dest(p, d) {
  if (d === "home") {
    const plot = plotOf(p);
    if (!plot) {
      try { p.onScreenDisplay.setActionBar("§c집터가 없어요 - 주거 섬 집터 사무소에서 살 수 있어요"); } catch (e) { }
      return undefined;
    }
    return plotEntry(plot);
  }
  return DATA.arrivals[d];
}
function portalTick() {
  const now = system.currentTick;
  for (const p of world.getPlayers()) {
    let hit;
    for (const pt of DATA.portals) if (inBox(p.location, pt.box)) { hit = pt; break; }
    if (!hit || (tpCooldown.get(p.id) ?? 0) > now) { portalTime.delete(p.id); continue; }
    if (inCombat(p)) {
      try { p.onScreenDisplay.setActionBar("§c전투 중에는 이동할 수 없어요 (10초)"); } catch (e) { }
      continue;
    }
    const n = (portalTime.get(p.id) ?? 0) + 1;
    portalTime.set(p.id, n);
    const label = hit.kind === "return" ? "§b허브로 귀환" : hit.label;
    if (n < 4) {
      try { p.onScreenDisplay.setActionBar(label + " §7- 잠시 서 계세요 " + "■".repeat(n) + "□".repeat(4 - n)); } catch (e) { }
      continue;
    }
    portalTime.delete(p.id);
    const d = dest(p, hit.dest);
    if (!d) { tpCooldown.set(p.id, now + 60); continue; }
    tp(p, d);
    tpCooldown.set(p.id, now + 60);
    try { p.playSound("mob.endermen.portal", { volume: 0.5 }); } catch (e) { }
  }
}

// ------------------------------------------------------------------ menu item, starter kit
function menuItem() {
  const it = new ItemStack(MENU_ITEM, 1);
  it.nameTag = MENU_NAME;
  it.setLore(["§7우클릭(길게 누르기)으로 메뉴 열기"]);
  try { it.lockMode = ItemLockMode.inventory ?? ItemLockMode.Inventory; } catch (e) { }
  it.keepOnDeath = true;
  return it;
}
function hasMenu(c) {
  for (let i = 0; i < c.size; i++) {
    const it = c.getItem(i);
    if (it && it.typeId === MENU_ITEM && it.nameTag === MENU_NAME) return true;
  }
  return false;
}
function giveMenu(p) {
  try {
    const c = p.getComponent("minecraft:inventory").container;
    if (!hasMenu(c)) {
      if (!c.getItem(8)) c.setItem(8, menuItem());
      else c.addItem(menuItem());
    }
  } catch (e) { }
}
function starterKit(p) {
  if (p.getDynamicProperty("sky:joined")) return;
  p.setDynamicProperty("sky:joined", true);
  addMoney(p, START_MONEY);
  try {
    const c = p.getComponent("minecraft:inventory").container;
    for (const [id, n] of [["minecraft:wooden_pickaxe", 1], ["minecraft:wooden_axe", 1], ["minecraft:wooden_sword", 1], ["minecraft:bread", 8]]) {
      c.addItem(new ItemStack(id, n));
    }
  } catch (e) { }
  system.runTimeout(() => {
    try {
      p.onScreenDisplay.setTitle("§b§l스카이젠", { subtitle: "§f하늘섬 군도에 오신 것을 환영합니다", fadeInDuration: 10, stayDuration: 80, fadeOutDuration: 20 });
      p.sendMessage("§b[스카이젠] §f기본 도구와 " + START_MONEY + "원을 받았어요. 핫바 9번 칸의 §l스카이젠 메뉴§r§f를 우클릭해 보세요.");
      p.sendMessage("§7낮(05~19시)에는 PvP가 꺼지고, 밤에는 안전구역 밖에서 PvP가 가능하며 죽으면 아이템을 떨어뜨립니다.");
    } catch (e) { }
  }, 40);
}

world.afterEvents.playerSpawn.subscribe((ev) => {
  const p = ev.player;
  spawnTick.set(p.id, system.currentTick);
  system.runTimeout(() => {
    // logged in inside a plot that is not (or no longer) theirs: put them outside, this is not a cheat
    const pl = plotOfPlayerPos(p.location);
    if (pl && !owns(p, pl) && !isAdmin(p)) tp(p, pl.outside);
    if (isBanned(p)) {
      p.sendMessage("§c영구밴된 플레이어입니다.");
      cmd('kick "' + p.name.replace(/"/g, "") + '" §c핵 사용으로 영구밴된 플레이어입니다');
      return;
    }
    if (ev.initialSpawn) starterKit(p);
    giveMenu(p);
    if (!isAdmin(p)) { try { p.setGameMode(GameMode.Adventure ?? GameMode.adventure); } catch (e) { } }
  }, 20);
});

// ------------------------------------------------------------------ forms
function shopForm(p, key) {
  if (key === "sell") return sellForm(p);
  const s = SHOPS[key];
  if (!s) return;
  const f = new ActionFormData().title(s.title).body("§f보유 금액: §6" + fmt(money(p)) + "원\n§7누를 때마다 한 묶음씩 구매합니다.");
  for (const it of s.items) f.button("§0" + it.name + " §8x" + it.n + "\n§2" + fmt(it.price) + "원");
  f.button("§c닫기");
  showForm(p, f).then((r) => {
    if (r.canceled || r.selection === undefined || r.selection >= s.items.length) return;
    const it = s.items[r.selection];
    if (money(p) < it.price) {
      p.sendMessage("§c돈이 부족해요. (" + fmt(money(p)) + " / " + fmt(it.price) + "원)");
      return;
    }
    const c = p.getComponent("minecraft:inventory").container;
    if (c.emptySlotsCount < 1) { p.sendMessage("§c인벤토리가 가득 찼어요."); return; }
    addMoney(p, -it.price);
    const left = c.addItem(new ItemStack(it.id, it.n));
    if (left) OW().spawnItem(left, p.location);
    p.playSound("random.orb");
    p.sendMessage("§a구매: " + it.name + " x" + it.n + " (-" + fmt(it.price) + "원)");
    system.runTimeout(() => shopForm(p, key), 4);
  });
}
function sellable(p) {
  const c = p.getComponent("minecraft:inventory").container;
  const tot = {};
  for (let i = 0; i < c.size; i++) {
    const it = c.getItem(i);
    if (!it || !SELL[it.typeId]) continue;
    tot[it.typeId] = (tot[it.typeId] ?? 0) + it.amount;
  }
  return tot;
}
function doSell(p, only) {
  const c = p.getComponent("minecraft:inventory").container;
  let earned = 0, count = 0;
  for (let i = 0; i < c.size; i++) {
    const it = c.getItem(i);
    if (!it || !SELL[it.typeId] || (only && it.typeId !== only)) continue;
    earned += SELL[it.typeId][0] * it.amount;
    count += it.amount;
    c.setItem(i, undefined);
  }
  if (count) {
    addMoney(p, earned);
    p.playSound("random.orb");
    p.sendMessage("§a" + count + "개를 팔아 §6" + fmt(earned) + "원§a을 벌었어요.");
  }
  return earned;
}
function sellForm(p) {
  const tot = sellable(p);
  const ids = Object.keys(tot);
  let all = 0;
  let lines = "";
  for (const id of ids) {
    all += SELL[id][0] * tot[id];
    lines += "§f" + SELL[id][1] + " §7x" + tot[id] + " §8→ §6" + fmt(SELL[id][0] * tot[id]) + "원\n";
  }
  const f = new ActionFormData().title("§l광물 판매소")
    .body("§f보유 금액: §6" + fmt(money(p)) + "원\n\n" + (ids.length ? lines : "§7팔 수 있는 물건이 없어요.\n§7원목 · 돌 · 석탄 · 철 · 금 · 다이아몬드를 가져오세요.\n") +
      "\n§8가격표: " + Object.keys(SELL).filter((k, i, a) => a.findIndex((x) => SELL[x][1] === SELL[k][1]) === i)
        .map((k) => SELL[k][1] + " " + SELL[k][0]).join(" · "));
  const opts = [];
  if (ids.length) { f.button("§2§l모두 팔기\n§r§6" + fmt(all) + "원"); opts.push(null); }
  for (const id of ids) { f.button("§0" + SELL[id][1] + "만 팔기\n§6" + fmt(SELL[id][0] * tot[id]) + "원"); opts.push(id); }
  f.button("§c닫기");
  showForm(p, f).then((r) => {
    if (r.canceled || r.selection === undefined || r.selection >= opts.length) return;
    doSell(p, opts[r.selection]);
    system.runTimeout(() => sellForm(p), 4);
  });
}

function guideForm(p) {
  const f = new ActionFormData().title("§l§b스카이젠 안내")
    .body([
      "§e낮 (05~19시) §f: PvP 불가, 죽어도 인벤토리 유지",
      "§c밤 (19~05시) §f: 안전구역 밖 PvP 가능, 죽으면 아이템 드롭",
      "§a안전구역 §f: 허브 · 주거 섬 · 마법 도서관 (밤에도 PvP 불가)",
      "",
      "§f1. 숲 섬에서 §2원목 · 돌§f을 캐요 (생성기는 몇 초 뒤 다시 생겨요)",
      "§f2. 허브 §b광물 판매소§f에 팔고 더 좋은 곡괭이를 사요",
      "§f3. 우주 광산선 §8석탄 · 철§f, 화산 섬 §6금 · 다이아몬드",
      "§f4. 우주선 §6개인 화로방§f에서 구우면 더 비싸게 팔려요",
      "§f5. 주거 섬 §e집터 사무소§f에서 집터를 사서 집을 지어요",
      "§f6. 마법 도서관에서 §d인첸트§f · 수리",
      "",
      "§4남의 집터에 핵으로 들어가면 자동으로 영구밴됩니다.",
    ].join("\n"))
    .button("§l메뉴 아이템 받기").button("§l내 정보").button("§c닫기");
  showForm(p, f).then((r) => {
    if (r.canceled) return;
    if (r.selection === 0) giveMenu(p);
    if (r.selection === 1) infoForm(p);
  });
}
function infoForm(p) {
  const plot = plotOf(p);
  const zone = safeZoneOf(p.location);
  const f = new MessageFormData().title("§l내 정보").body([
    "§f이름: §e" + p.name,
    "§f돈: §6" + fmt(money(p)) + "원",
    "§f집터: " + (plot ? "§a#" + plot.id : "§7없음"),
    "§f지금 위치: " + (zone ? "§a안전구역" : "§cPvP 구역"),
    "§f시간: " + (isNight() ? "§c밤 - PvP 가능" : "§e낮 - PvP 불가"),
  ].join("\n")).button1("§l확인").button2("§l메뉴");
  showForm(p, f).then((r) => { if (!r.canceled && r.selection === 1) menuForm(p); });
}

const warmups = new Map();
function warmTp(p, d, label) {
  if (!d) return;
  if (safeZoneOf(p.location) || !isNight()) { tp(p, d); p.playSound("mob.endermen.portal", { volume: 0.5 }); return; }
  if (inCombat(p)) { p.sendMessage("§c전투 중에는 이동할 수 없어요."); return; }
  const start = { ...p.location };
  let left = 5;
  const id = system.runInterval(() => {
    const l = p.location;
    if (!p.isValid || Math.hypot(l.x - start.x, l.z - start.z) > 0.6 || inCombat(p)) {
      system.clearRun(id);
      try { p.onScreenDisplay.setActionBar("§c움직여서 이동이 취소됐어요"); } catch (e) { }
      return;
    }
    if (left <= 0) {
      system.clearRun(id);
      tp(p, d);
      p.playSound("mob.endermen.portal", { volume: 0.5 });
      return;
    }
    try { p.onScreenDisplay.setActionBar("§b" + label + " §f이동까지 " + left + "초 (움직이지 마세요)"); } catch (e) { }
    left--;
  }, 20);
}
function menuForm(p) {
  const plot = plotOf(p);
  const insideOwn = plot && plotOfPlayerPos(p.location) === plot;
  const f = new ActionFormData().title("§l§b스카이젠 메뉴")
    .body("§f돈: §6" + fmt(money(p)) + "원   §f" + (isNight() ? "§c밤 (PvP)" : "§e낮 (PvP 불가)"));
  const acts = [];
  f.button("§l허브로 이동\n§r§8밤 · PvP 구역에서는 5초 대기"); acts.push(() => warmTp(p, DATA.arrivals.hub, "허브"));
  if (plot) {
    if (insideOwn) { f.button("§l집에서 나가기\n§r§8집터 앞 길로"); acts.push(() => tp(p, plot.outside)); }
    else { f.button("§l내 집터로 이동\n§r§8#" + plot.id); acts.push(() => warmTp(p, plotEntry(plot), "내 집터")); }
  }
  f.button("§l내 정보"); acts.push(() => infoForm(p));
  f.button("§l규칙 / 도움말"); acts.push(() => guideForm(p));
  if (safeZoneOf(p.location)) {
    f.button("§l광물 판매\n§r§8안전구역에서만"); acts.push(() => sellForm(p));
  }
  f.button("§c닫기"); acts.push(() => { });
  showForm(p, f).then((r) => { if (!r.canceled && r.selection !== undefined) acts[r.selection](); });
}

function plotClerkForm(p) {
  const mine = plotOf(p);
  const free = DATA.plots.filter((pl) => !PLOTS[pl.id]);
  const f = new ActionFormData().title("§l§e집터 사무소").body(
    "§f보유 금액: §6" + fmt(money(p)) + "원\n§f내 집터: " + (mine ? "§a#" + mine.id : "§7없음") +
    "\n§f빈 집터: §a" + free.length + "§f / " + DATA.plots.length + "\n\n§7· 1인 1집터 · 집터 안(허용 블록 위)에서만 건축\n§7· 출입은 집터 앞 기둥의 버튼으로");
  const acts = [];
  if (mine) {
    f.button("§l내 집터로 이동\n§r§8#" + mine.id); acts.push(() => tp(p, plotEntry(mine)));
    f.button("§c§l집터 포기\n§r§8건물이 모두 지워져요 (절반 환불)"); acts.push(() => abandonForm(p, mine));
  } else {
    f.button("§2§l집터 구매\n§r§8빈 집터 목록"); acts.push(() => plotListForm(p));
  }
  f.button("§c닫기"); acts.push(() => { });
  showForm(p, f).then((r) => { if (!r.canceled && r.selection !== undefined) acts[r.selection](); });
}
function plotListForm(p) {
  const free = DATA.plots.filter((pl) => !PLOTS[pl.id]);
  if (!free.length) { p.sendMessage("§c빈 집터가 없어요."); return; }
  const f = new ActionFormData().title("§l빈 집터").body("§f보유 금액: §6" + fmt(money(p)) + "원\n§7지도판(사무소 옆)에서 위치를 확인하세요.");
  for (const pl of free) f.button("§0집터 #" + pl.id + (pl.price >= 4000 ? " §3(라군 앞)" : "") + "\n§2" + fmt(pl.price) + "원");
  showForm(p, f).then((r) => {
    if (r.canceled || r.selection === undefined) return;
    buyForm(p, free[r.selection]);
  });
}
function buyForm(p, pl) {
  if (plotOf(p)) { p.sendMessage("§c이미 집터가 있어요. (1인 1집터)"); return; }
  if (PLOTS[pl.id]) { p.sendMessage("§c이미 팔린 집터입니다."); return; }
  const f = new MessageFormData().title("§l집터 #" + pl.id + " 구매")
    .body("§f가격: §6" + fmt(pl.price) + "원\n§f보유: §6" + fmt(money(p)) + "원\n\n§715x15 크기, 위로 24칸까지 지을 수 있어요.\n§7사고 나면 집터 안으로 이동합니다.")
    .button1("§2§l구매").button2("§l취소");
  showForm(p, f).then((r) => {
    if (r.canceled || r.selection !== 0) return;
    if (plotOf(p) || PLOTS[pl.id]) { p.sendMessage("§c구매할 수 없어요."); return; }
    if (money(p) < pl.price) { p.sendMessage("§c돈이 부족해요. (" + fmt(money(p)) + " / " + fmt(pl.price) + "원)"); return; }
    for (const o of world.getPlayers()) {
      if (o.id !== p.id && inBox(o.location, pl.zone, 0.3)) { p.sendMessage("§c지금은 살 수 없어요."); return; }
    }
    addMoney(p, -pl.price);
    PLOTS[pl.id] = { owner: p.name, ownerId: p.id, since: Date.now() };
    save("sky:plots", PLOTS);
    world.sendMessage("§e[집터] §f" + p.name + "님이 집터 #" + pl.id + "을(를) 샀어요!");
    p.playSound("random.levelup");
    tp(p, plotEntry(pl));
    refreshPlot(pl, true);
  });
}
function abandonForm(p, pl) {
  const f = new MessageFormData().title("§c§l집터 포기")
    .body("§f집터 #" + pl.id + "을(를) 포기할까요?\n§c집터 안의 블록과 상자 속 물건이 모두 지워집니다.\n§f환불: §6" + fmt(Math.floor(pl.price / 2)) + "원")
    .button1("§c§l포기").button2("§l취소");
  showForm(p, f).then((r) => {
    if (r.canceled || r.selection !== 0 || !owns(p, pl)) return;
    for (const o of world.getPlayers()) if (inBox(o.location, pl.zone, 0)) tp(o, pl.outside);
    delete PLOTS[pl.id];
    save("sky:plots", PLOTS);
    addMoney(p, Math.floor(pl.price / 2));
    if (!PENDING_RESET.includes(pl.id)) PENDING_RESET.push(pl.id);
    save("sky:plotreset", PENDING_RESET);
    p.sendMessage("§e집터 #" + pl.id + "을(를) 포기했어요. (+" + fmt(Math.floor(pl.price / 2)) + "원)");
    refreshPlot(pl, true);
  });
}
function resetPlot(pl) {
  const [x1, y1, z1, x2, y2, z2] = pl.interior;
  const f = pl.floor;
  if (!getBlock(x1, f, z1) || !getBlock(x2, f, z2)) return false;
  for (let y = f + 1; y <= y2; y += 12) cmd(`fill ${x1} ${y} ${z1} ${x2} ${Math.min(y + 11, y2)} ${z2} air`);
  cmd(`fill ${x1} ${y1} ${z1} ${x2} ${f - 1} ${z2} dirt`);
  cmd(`fill ${x1} ${f} ${z1} ${x2} ${f} ${z2} grass_block`);
  placeButtons(pl);
  return true;
}
const plotShown = {};      // sign text last written
const mapShown = {};       // board pixel last written (the board and the sign can sit in different chunks)
function refreshPlot(pl, force) {
  const o = PLOTS[pl.id];
  const text = o ? "§l§e집터 #" + pl.id + "\n§r§c주인\n§f" + o.owner : "§l§e집터 #" + pl.id + "\n§r§a판매 중\n§f" + fmt(pl.price) + "원";
  if (force || plotShown[pl.id] !== text) {
    const s = getBlock(pl.sign[0], pl.sign[1], pl.sign[2]);
    if (s) {
      try {
        const sc = s.getComponent("minecraft:sign");
        if (sc) sc.setText(text);
        plotShown[pl.id] = text;
      } catch (e) { }
    }
  }
  const px = o ? "minecraft:red_concrete" : "minecraft:lime_concrete";
  if (pl.map && (force || mapShown[pl.id] !== px) && setBlock(pl.map[0], pl.map[1], pl.map[2], px)) mapShown[pl.id] = px;
}
function plotSweep() {
  for (const pl of DATA.plots) { refreshPlot(pl, false); placeButtons(pl); }
  if (PENDING_RESET.length) {
    const left = PENDING_RESET.filter((id) => !(PLOT_BY_ID[id] && !PLOTS[id] && resetPlot(PLOT_BY_ID[id])));
    if (left.length !== PENDING_RESET.length) { PENDING_RESET = left; save("sky:plotreset", PENDING_RESET); }
  }
}

world.afterEvents.buttonPush.subscribe((ev) => {
  const p = ev.source;
  if (!p || p.typeId !== "minecraft:player") return;
  const b = ev.block;
  for (const pl of DATA.plots) {
    if (b.x === pl.btnOut[0] && b.y === pl.btnOut[1] && b.z === pl.btnOut[2]) {
      const o = PLOTS[pl.id];
      if (!o) { buyForm(p, pl); return; }
      if (owns(p, pl) || isAdmin(p)) { tp(p, plotEntry(pl)); p.playSound("random.door_open"); return; }
      p.onScreenDisplay.setActionBar("§c" + o.owner + "님의 집터입니다 (주인만 들어갈 수 있어요)");
      return;
    }
    if (b.x === pl.btnIn[0] && b.y === pl.btnIn[1] && b.z === pl.btnIn[2]) {
      tp(p, pl.outside);
      p.playSound("random.door_close");
      return;
    }
  }
});

world.beforeEvents.playerInteractWithEntity.subscribe((ev) => {
  const t = ev.target;
  if (!t || t.typeId !== "minecraft:npc") return;
  const tags = t.getTags();
  const tag = tags.find((s) => s.startsWith("sky_"));
  if (!tag) return;
  ev.cancel = true;
  const p = ev.player;
  system.run(() => {
    if (tag === "sky_guide") guideForm(p);
    else if (tag === "sky_plot_clerk") plotClerkForm(p);
    else if (tag.startsWith("sky_shop_")) shopForm(p, tag === "sky_shop_magic2" ? "magic" : tag.slice(9));
  });
});

world.afterEvents.itemUse.subscribe((ev) => {
  const p = ev.source, it = ev.itemStack;
  if (!p || !it || it.typeId !== MENU_ITEM || it.nameTag !== MENU_NAME) return;
  menuForm(p);
});

// ------------------------------------------------------------------ NPCs (summoned when a player is near)
function npcTick(force) {
  const players = world.getPlayers();
  for (const n of DATA.npcs) {
    if (!force && !players.some((p) => Math.hypot(p.location.x - n.x, p.location.z - n.z) < 48)) continue;
    let ents = [];
    try { ents = OW().getEntities({ type: "minecraft:npc", tags: [n.tag], location: { x: n.x, y: n.y, z: n.z }, maxDistance: 8 }); } catch (e) { continue; }
    if (!ents.length) {
      try {
        const e = OW().spawnEntity("minecraft:npc", { x: n.x, y: n.y, z: n.z });
        e.nameTag = n.name;
        e.addTag(n.tag);
        e.addTag("sky_npc");
        e.teleport({ x: n.x, y: n.y, z: n.z }, { facingLocation: { x: n.face[0], y: n.face[1], z: n.face[2] } });
      } catch (e) { }
    } else {
      for (let i = 1; i < ents.length; i++) try { ents[i].remove(); } catch (e) { }
      const e = ents[0], l = e.location;
      if (Math.hypot(l.x - n.x, l.z - n.z) > 0.6 || Math.abs(l.y - n.y) > 1) {
        try { e.teleport({ x: n.x, y: n.y, z: n.z }, { facingLocation: { x: n.face[0], y: n.face[1], z: n.face[2] } }); } catch (e2) { }
      }
    }
  }
}

// ------------------------------------------------------------------ HUD + periodic jobs
function hud() {
  const night = isNight();
  for (const p of world.getPlayers()) {
    if ((portalTime.get(p.id) ?? 0) > 0) continue;
    const z = safeZoneOf(p.location);
    const room = furnaceRoomOf(p.location);
    let where = z ? "§a[안전구역]" : night ? "§c[PvP 구역]" : "§e[PvP 구역 · 낮이라 공격 불가]";
    if (room) where = "§6[개인 화로방 " + room.id + "]" + (night ? " §c밤 PvP" : "");
    try { p.onScreenDisplay.setActionBar(where + " §7| " + (night ? "§c밤" : "§e낮") + " §7| §6" + fmt(money(p)) + "원"); } catch (e) { }
    if (!isAdmin(p) && lower(p.getGameMode()) !== "adventure") {
      try { p.setGameMode(GameMode.Adventure ?? GameMode.adventure); } catch (e) { }
    }
  }
}

let started = false;
function init() {
  if (started) return;
  started = true;
  PLOTS = store("sky:plots", {});
  BANS = store("sky:bans", []);
  PENDING_RESET = store("sky:plotreset", []);
  try {
    const o = moneyObj();
    world.scoreboard.setObjectiveAtDisplaySlot(DisplaySlotId.Sidebar, { objective: o, sortOrder: ObjectiveSortOrder.Descending });
  } catch (e) { }
  try { world.gameRules.doMobSpawning = false; } catch (e) { }
  applyTime(false);
  system.runInterval(() => applyTime(true), 20);
  system.runInterval(banCheck, 10);
  system.runInterval(furnaceTick, 10);
  system.runInterval(portalTick, 5);
  system.runInterval(hud, 20);
  system.runInterval(sweepGens, 100);
  system.runInterval(plotSweep, 100);
  system.runInterval(() => npcTick(false), 40);
  console.warn("[skygen] ready: gens=" + DATA.gens.length + " plots=" + DATA.plots.length + " rooms=" + DATA.furnace.length +
    " safe=" + SAFE.length + " owned=" + Object.keys(PLOTS).length + " bans=" + BANS.length);
}
if (world.afterEvents.worldLoad) world.afterEvents.worldLoad.subscribe(() => init());
system.runTimeout(() => init(), 20);

// ------------------------------------------------------------------ admin / test events
system.afterEvents.scriptEventReceive.subscribe((ev) => {
  const id = ev.id, msg = (ev.message || "").trim();
  if (id === "sky:diag") {
    let gensOk = 0, gensLoaded = 0;
    for (const k in GENS) {
      const g = GENS[k];
      const b = getBlock(g[0], g[1], g[2]);
      if (b) { gensLoaded++; if (b.typeId === g[3]) gensOk++; }
    }
    console.warn("[skygen] diag night=" + isNight() + " pvp=" + world.gameRules.pvp + " keepInventory=" + world.gameRules.keepInventory +
      " gensLoaded=" + gensLoaded + " gensOk=" + gensOk + " plots=" + DATA.plots.length + " owned=" + Object.keys(PLOTS).length +
      " bans=" + BANS.length + " npcs=" + DATA.npcs.length);
  } else if (id === "sky:gentest") {
    // simulate mining the first loaded generator of a kind: break -> bedrock -> regrow
    const kind = msg || "stone";
    for (const k in GENS) {
      const g = GENS[k];
      if (g[4] !== kind) continue;
      const b = getBlock(g[0], g[1], g[2]);
      if (!b) continue;
      b.setType("minecraft:bedrock");
      pendingGen.set(k, system.currentTick + g[5] * 20);
      system.runTimeout(() => { restoreGen(k); pendingGen.delete(k); }, g[5] * 20);
      console.warn("[skygen] gentest " + kind + " at " + k + " -> bedrock, back in " + g[5] + "s");
      return;
    }
    console.warn("[skygen] gentest: no loaded " + kind + " generator");
  } else if (id === "sky:unban") {
    const before = BANS.length;
    BANS = BANS.filter((b) => b.name !== msg);
    save("sky:bans", BANS);
    console.warn("[skygen] unban " + msg + " removed=" + (before - BANS.length));
  } else if (id === "sky:bans") {
    console.warn("[skygen] bans: " + BANS.map((b) => b.name).join(", "));
  } else if (id === "sky:money") {
    const [name, amt] = msg.split(" ");
    const p = world.getPlayers({ name });
    if (p.length) { addMoney(p[0], parseInt(amt) || 0); console.warn("[skygen] money " + name + " " + money(p[0])); }
  } else if (id === "sky:plotfree") {
    const pid = parseInt(msg);
    const pl = PLOT_BY_ID[pid];
    if (pl) for (const o of world.getPlayers()) if (inBox(o.location, pl.zone, 0)) tp(o, pl.outside);
    if (PLOTS[pid]) { delete PLOTS[pid]; save("sky:plots", PLOTS); }
    if (!PENDING_RESET.includes(pid)) { PENDING_RESET.push(pid); save("sky:plotreset", PENDING_RESET); }
    console.warn("[skygen] plot " + pid + " freed");
  } else if (id === "sky:plotgive") {
    const [pid, name] = msg.split(" ");
    PLOTS[parseInt(pid)] = { owner: name, ownerId: "", since: Date.now() };
    save("sky:plots", PLOTS);
    console.warn("[skygen] plot " + pid + " -> " + name);
  } else if (id === "sky:npctest") {
    npcTick(true);
    let n = 0;
    try { n = OW().getEntities({ type: "minecraft:npc", tags: ["sky_npc"] }).length; } catch (e) { }
    console.warn("[skygen] npctest npcs=" + n + "/" + DATA.npcs.length);
  } else if (id === "sky:roomtest") {
    // occupancy logic without players: fake occupants
    const r = DATA.furnace[0];
    roomOcc[r.id] = new Set(["a"]);
    setBlock(r.lamp[0], r.lamp[1], r.lamp[2], "minecraft:red_concrete");
    const b = getBlock(r.lamp[0], r.lamp[1], r.lamp[2]);
    console.warn("[skygen] roomtest lamp=" + (b ? b.typeId : "unloaded"));
    roomOcc[r.id] = new Set();
    setBlock(r.lamp[0], r.lamp[1], r.lamp[2], "minecraft:lime_concrete");
  }
});
